spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 3MB
      max-request-size: 10MB
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.100.89.20:3306/salt_hub?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: lw091211
  sa-token:
    token-name: jwt
    timeout: 604800
    activity-timeout: -1
    allow-concurrent-login: false
    is-share: false
    token-style: uuid
    is-v: false
    is-read-cookie: false

server:
  ssl:
    key-store: classpath:tomcat.keystore
    key-store-password: 123456
    key-alias: tomcat
    key-store-type: JKS
  port: 443

mybatis-plus:
  global-config:
    banner: false
