spring:
  redis:
    host: 8.140.10.177
    port: 6379
    database: 0
    jedis:
      pool:
        max-active: 50
        max-wait: 3000
        max-idle: 20
        min-idle: 5
    connect-timeout: 5000
    password: 123456

knife4j:
  basic:
    enable: true
    username: 123456
    password: 123456
  setting:
    language: zh-CN
  enable: true

